2025-06-13 18:02:51 - api_server - ERROR - 任务 64eb1258-67ce-4320-b33c-7e117496691f 解析失败: No module named 'loguru'
2025-06-13 18:02:51 - api_server - ERROR - ❌ 任务 64eb1258-67ce-4320-b33c-7e117496691f 解析失败: No module named 'loguru'
2025-06-13 18:02:51 - api_server - ERROR - 文档解析失败，停止后续流程: 64eb1258-67ce-4320-b33c-7e117496691f
2025-06-13 18:07:36 - ContentAnalyzerService - ERROR - 内容分析分析失败 - 任务ID: 4797258a-80bd-4894-b4ab-7d55f6bd0df7, 错误: name 'parsing_result' is not defined
2025-06-17 10:12:13 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 10:12:14 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 10:12:16 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 10:12:17 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 10:12:19 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 11:09:29 - __main__ - ERROR - ❌ 删除现有记录失败: _FetchObjectsQueryExecutor.fetch_objects() got an unexpected keyword argument 'where'
2025-06-17 11:09:29 - __main__ - ERROR - ❌ 处理文档失败: _FetchObjectsQueryExecutor.fetch_objects() got an unexpected keyword argument 'where'
2025-06-17 11:19:10 - src.utils.enhanced_analyzer - ERROR - Word文档解析失败: "There is no item named 'NULL' in the archive"
2025-06-17 11:19:10 - __main__ - ERROR - ❌ 处理Word文档失败 D:\knowledge_base\链数_LS\需求文档\LS-1(YS-72)_需求文档-链数一期V1.8.docx: object of type 'coroutine' has no len()
2025-06-17 11:19:10 - __main__ - ERROR - ❌ 处理文档失败: object of type 'coroutine' has no len()
2025-06-17 11:20:31 - src.utils.enhanced_analyzer - ERROR - Word文档解析失败: "There is no item named 'NULL' in the archive"
2025-06-17 12:25:00 - __main__ - ERROR - ❌ 处理Word文档失败 D:\knowledge_base\链数_LS\需求文档\LS-1(YS-72)_需求文档-链数一期V1.8.docx: KnowledgeBaseInitializer.extract_text_from_file() takes 1 positional argument but 2 were given
2025-06-17 12:25:00 - __main__ - ERROR - ❌ 处理文档失败: KnowledgeBaseInitializer.extract_text_from_file() takes 1 positional argument but 2 were given
2025-06-17 14:30:55 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:30:55 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:30:56 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:30:56 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:30:56 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:44:46 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:44:46 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:44:46 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:44:46 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 14:44:46 - ContentAnalyzerService - ERROR - 历史内容搜索失败: Query call with protocol GRPC search failed with message could not find class Documents in schema.
2025-06-17 15:42:43 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 15:42:43 - ContentAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 15:42:57 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 15:42:57 - AIAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 15:42:58 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 15:42:58 - AIAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:16 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:16 - DocumentParserService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:21 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:21 - ContentAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:34 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:34 - ContentAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:35 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:35 - ContentAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:37 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:37 - ContentAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:38 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:38 - AIAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:06:39 - src.utils.volcengine_client - ERROR - 火山引擎API调用失败: Connection error.
2025-06-17 16:06:39 - AIAnalyzerService - ERROR - LLM调用失败: Connection error.
2025-06-17 16:07:55 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A945382C50>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 234d873a-30ac-4a8b-a394-d16f5e5eedcf)')
2025-06-17 16:08:03 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C765A1AC50>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 906e2223-e73f-4ad4-93eb-693170b9f5db)')
2025-06-17 16:08:25 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001770010E990>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: a308ea58-57b3-42d0-a091-cb61b77aa524)')
2025-06-17 16:08:44 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000011BC5489C10>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 78f5756e-f341-406c-b385-5ae77d64d0ec)')
2025-06-17 16:08:55 - api_server - ERROR - 任务 1d828620-a205-487b-ba0b-9e808cab885f 解析失败: name 'file_content' is not defined
2025-06-17 16:08:55 - api_server - ERROR - ❌ 任务 1d828620-a205-487b-ba0b-9e808cab885f 解析失败: name 'file_content' is not defined
2025-06-17 16:08:55 - api_server - ERROR - 文档解析失败，停止后续流程: 1d828620-a205-487b-ba0b-9e808cab885f
2025-06-17 16:13:47 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254EB97E450>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 7f149099-dc64-419e-bb8f-7e9bb3389081)')
2025-06-17 16:15:42 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001DA34AF19D0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: f5ffe0a0-6739-422e-a677-8fa85dd31434)')
2025-06-17 16:15:43 - api_server - ERROR - 任务 aec6136e-5836-49b5-9e82-f1edc39e75ac 解析失败: name 'file_content' is not defined
2025-06-17 16:15:43 - api_server - ERROR - ❌ 任务 aec6136e-5836-49b5-9e82-f1edc39e75ac 解析失败: name 'file_content' is not defined
2025-06-17 16:15:43 - api_server - ERROR - 文档解析失败，停止后续流程: aec6136e-5836-49b5-9e82-f1edc39e75ac
2025-06-17 16:16:09 - api_server - ERROR - 任务 9656d6d8-c1ea-48cc-b934-d8c7c5d114a0 解析失败: name 'file_content' is not defined
2025-06-17 16:16:09 - api_server - ERROR - ❌ 任务 9656d6d8-c1ea-48cc-b934-d8c7c5d114a0 解析失败: name 'file_content' is not defined
2025-06-17 16:16:09 - api_server - ERROR - 文档解析失败，停止后续流程: 9656d6d8-c1ea-48cc-b934-d8c7c5d114a0
2025-06-17 16:16:22 - api_server - ERROR - 任务 0bb72504-b846-48ed-b512-2dcc686bbe82 解析失败: name 'file_content' is not defined
2025-06-17 16:16:22 - api_server - ERROR - ❌ 任务 0bb72504-b846-48ed-b512-2dcc686bbe82 解析失败: name 'file_content' is not defined
2025-06-17 16:16:22 - api_server - ERROR - 文档解析失败，停止后续流程: 0bb72504-b846-48ed-b512-2dcc686bbe82
2025-06-17 16:19:28 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D277A8E550>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 51e4fbac-a50b-4b01-8f07-7b51c7d5fcde)')
2025-06-17 16:21:44 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001817077DE50>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 72ccb9d4-6427-4e3c-ba51-571c69f2a0f4)')
2025-06-17 16:23:39 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000216641E3990>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: cbc580ac-a058-4228-a12e-6b99d3b213b8)')
2025-06-17 16:23:40 - api_server - ERROR - Word文档解析失败: 'EnhancedAnalyzer' object has no attribute 'analyze_file'
2025-06-17 16:28:10 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D19A315B50>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 1f789fb7-9f63-4cbf-af64-2ddf003e2f7e)')
2025-06-17 16:30:03 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028B00054590>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: d7dca2bd-4e97-42b0-aa5b-b1513f91b9ef)')
2025-06-17 16:31:13 - api_server - ERROR - 分析服务管理器初始化失败: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027BDF492A10>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: c8925c7f-e334-4878-a533-5331316e772c)')
